#!/bin/bash
echo $XDG_CURRENT_DESKTOP
case $XDG_CURRENT_DESKTOP in
    MATE)
        echo 'Installing mate-screensaver'
        apt install mate-screensaver
        ;;
    GNOME)
        echo 'Installing gnome-screensaver'
        apt install gnome-screensaver
        ;;
esac
